name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3

        - name: Set up Docker Buildx
          id: docker_buildx
          uses: docker/setup-buildx-action@v2

        - name: lint Dockerfile
          uses: hadolint/hadolint-action@v3.1.0
          with:
            dockerfile: Dockerfile
            failure-threshold: error
            recursive: false
            output-file: /dev/stdout
            no-color: false
            no-fail: false
            verbose: false
            format: tty
        
        - name: build Docker container
          if: github.event_name != 'pull_request'
          run: |
            docker build .
            docker system df